/**
 * @file        設計令牌
 * @description 全域設計令牌，定義亮色/暗色主題的顏色、陰影、字體等
 * @lastUpdate  2026-03-22 19:56:42
 * @author      Daniel Chung
 * @version     1.1.0
 */

import type { ShellTokens, ContentTokens } from '../../services/api';

export const lightColors = {
  primary: '#1e40af',
  success: '#22c55e',
  warning: '#f59e0b',
  error: '#dc2626',
  info: '#1e40af',
  bgBase: '#696d6f',
  textBase: '#030213',
  tableExpandedRowBg: '#f0f4ff',
  tableHeaderBg: '#f0f4ff',
  siderBg: '#f8fafc',
  headerBg: '#ffffff',
  headerShadow: '0 2px 8px rgba(0, 0, 0, 0.08)',
  siderShadow: '2px 0 8px rgba(0, 0, 0, 0.06)',
  cardShadow: '0 6px 24px rgba(30, 64, 175, 0.25)',
  cardShadowHover: '0 12px 40px rgba(30, 64, 175, 0.35)',
  cardShadowSecondary: '0 12px 40px rgba(30, 64, 175, 0.35)',
  siderBorder: '#e2e8f0',
  chatInputBg: '#f1f5f9',
  chatUserBubble: '#dbeafe',
  chatAssistantBubble: '#e2e8f0',
  textSecondary: '#64748b',
  iconDefault: '#64748b',
  iconHover: '#1e40af',
  btnClear: '#f59e0b',
  btnClearHover: '#d97706',
  btnSend: '#1e40af',
  btnSendHover: '#1e3a8a',
  btnText: '#030213',
};

export const darkColors = {
  primary: '#3b82f6',
  success: '#22c55e',
  warning: '#f59e0b',
  error: '#ef4444',
  info: '#3b82f6',
  bgBase: '#0f172a',
  textBase: '#f1f5f9',
  tableExpandedRowBg: '#0a1120',
  tableHeaderBg: '#1a2235',
  siderBg: '#0c1425',
  headerBg: '#0c1425',
  headerShadow: '0 2px 8px rgba(0, 0, 0, 0.4)',
  siderShadow: '2px 0 8px rgba(0, 0, 0, 0.3)',
  cardShadow: '0 6px 24px rgba(100, 80, 220, 0.35)',
  cardShadowHover: '0 12px 40px rgba(100, 80, 220, 0.50)',
  cardShadowSecondary: '0 12px 40px rgba(100, 80, 220, 0.50)',
  siderBorder: '#334155',
  chatInputBg: '#1e293b',
  chatUserBubble: '#1e3a8a',
  chatAssistantBubble: '#1e293b',
  textSecondary: '#8892a0',
  iconDefault: '#8892a0',
  iconHover: '#ffffff',
  btnClear: '#f59e0b',
  btnClearHover: '#d97706',
  btnSend: '#3b82f6',
  btnSendHover: '#2563eb',
  btnText: '#ffffff',
};

export const DEFAULT_SHELL_TOKENS: ShellTokens = {
  siderBg: '#1e293b',
  headerBg: '#0f172a',
  menuItemColor: '#94a3b8',
  menuItemHoverBg: '#334155',
  menuItemSelectedBg: '#3b82f6',
  menuItemSelectedColor: '#ffffff',
  logoColor: '#ffffff',
  siderBorder: '#334155',
  headerShadow: '0 2px 8px rgba(0, 0, 0, 0.4)',
  siderShadow: '2px 0 8px rgba(0, 0, 0, 0.3)',
};

const DEFAULT_FONT_FAMILY =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif";

export const DEFAULT_CONTENT_LIGHT_TOKENS: ContentTokens = {
  colorPrimary: lightColors.primary,
  colorSuccess: lightColors.success,
  colorWarning: lightColors.warning,
  colorError: lightColors.error,
  colorInfo: lightColors.info,
  colorBgBase: lightColors.bgBase,
  colorTextBase: lightColors.textBase,
  pageBg: '#e8eaed',
  contentBg: '#ffffff',
  containerBg: '#ffffff',
  borderRadius: 10,
  fontFamily: DEFAULT_FONT_FAMILY,
  boxShadow: lightColors.cardShadow,
  boxShadowSecondary: lightColors.cardShadowSecondary,
  tableExpandedRowBg: lightColors.tableExpandedRowBg,
  tableHeaderBg: lightColors.tableHeaderBg,
  tableRowHoverBg: '#e6f0ff',
  chatInputBg: lightColors.chatInputBg,
  chatUserBubble: lightColors.chatUserBubble,
  chatAssistantBubble: lightColors.chatAssistantBubble,
  textSecondary: lightColors.textSecondary,
  iconDefault: lightColors.iconDefault,
  iconHover: lightColors.iconHover,
  btnClear: lightColors.btnClear,
  btnClearHover: lightColors.btnClearHover,
  btnSend: lightColors.btnSend,
  btnSendHover: lightColors.btnSendHover,
  btnText: lightColors.btnText,
  cardShadow: lightColors.cardShadow,
  cardShadowHover: lightColors.cardShadowHover,
  tableShadow: '0 2px 8px rgba(0, 0, 0, 0.06)',
  bgOpacity: 100,
};

export const DEFAULT_CONTENT_DARK_TOKENS: ContentTokens = {
  colorPrimary: darkColors.primary,
  colorSuccess: darkColors.success,
  colorWarning: darkColors.warning,
  colorError: darkColors.error,
  colorInfo: darkColors.info,
  colorBgBase: darkColors.bgBase,
  colorTextBase: darkColors.textBase,
  pageBg: '#0a0f1a',
  contentBg: '#0f172a',
  containerBg: '#1e293b',
  borderRadius: 10,
  fontFamily: DEFAULT_FONT_FAMILY,
  boxShadow: darkColors.cardShadow,
  boxShadowSecondary: darkColors.cardShadowSecondary,
  tableExpandedRowBg: darkColors.tableExpandedRowBg,
  tableHeaderBg: darkColors.tableHeaderBg,
  tableRowHoverBg: '#1a2744',
  chatInputBg: darkColors.chatInputBg,
  chatUserBubble: darkColors.chatUserBubble,
  chatAssistantBubble: darkColors.chatAssistantBubble,
  textSecondary: darkColors.textSecondary,
  iconDefault: darkColors.iconDefault,
  iconHover: darkColors.iconHover,
  btnClear: darkColors.btnClear,
  btnClearHover: darkColors.btnClearHover,
  btnSend: darkColors.btnSend,
  btnSendHover: darkColors.btnSendHover,
  btnText: darkColors.btnText,
  cardShadow: darkColors.cardShadow,
  cardShadowHover: darkColors.cardShadowHover,
  tableShadow: '0 2px 8px rgba(0, 0, 0, 0.3)',
  bgOpacity: 100,
};
